# Generated by Django 3.1.6 on 2021-02-21 14:25

import api.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('video_name', models.CharField(default='None', max_length=100, primary_key=True, serialize=False)),
                ('original_video', models.FileField(default=None, upload_to='')),
                ('labeld_video', models.FileField(blank=True, default=None, upload_to='')),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('tracklet', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_cars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('begin_frame', models.IntegerField()),
                ('exit_frame', models.IntegerField()),
                ('car_type', models.CharField(max_length=100)),
                ('api', models.ForeignKey(db_column='api', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.api')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('car_type', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=api.models.get_image_filename, verbose_name='Image')),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.car')),
            ],
        ),
    ]
