# Generated by Django 3.1.5 on 2021-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=None)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
