# Generated by Django 3.1.3 on 2021-02-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='video_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
