# Generated by Django 3.1.5 on 2021-01-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='frameImg',
            field=models.ImageField(default=None, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
