# Generated by Django 3.1.5 on 2021-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210124_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='frameImg',
        ),
        migrations.AddField(
            model_name='api',
            name='frameImgs',
            field=models.ImageField(default=None, null=True, upload_to='upload/image/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='video',
            field=models.FileField(upload_to='upload/video/'),
        ),
    ]
