# Generated by Django 3.1.5 on 2021-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210124_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='video',
            new_name='original_video',
        ),
        migrations.AddField(
            model_name='api',
            name='tracking_file',
            field=models.FileField(null=True, upload_to='upload/text/'),
        ),
        migrations.AddField(
            model_name='api',
            name='tracking_video',
            field=models.FileField(null=True, upload_to='upload/video/'),
        ),
    ]
