# Generated by Django 3.1.3 on 2021-01-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210125_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='frameImgs',
            field=models.ImageField(default=None, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='original_video',
            field=models.FileField(upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='tracking_file',
            field=models.FileField(null=True, upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='tracking_video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
