# Generated by Django 3.1.5 on 2021-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210210_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='count',
            field=models.FileField(default=None, null=True, upload_to='text/'),
        ),
    ]
