# Generated by Django 3.1.5 on 2021-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210210_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='labeld_video',
            field=models.FileField(default=None, null=True, upload_to='video/'),
        ),
    ]
