# Generated by Django 3.1.5 on 2021-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210210_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='count',
            field=models.FileField(blank=True, default=None, upload_to='text/'),
        ),
    ]
