# Generated by Django 3.1.5 on 2021-02-11 10:52

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210210_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='frameImgs',
        ),
        migrations.AlterField(
            model_name='api',
            name='labeld_video',
            field=models.FileField(blank=True, default=None, upload_to='video/'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.get_image_filename, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.api')),
            ],
        ),
    ]
