# Generated by Django 3.1.5 on 2021-02-11 12:33

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210211_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.get_image_filename, verbose_name='Image')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
