# Generated by Django 3.1.5 on 2021-02-11 12:54

import api.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210211_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiimages',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.api'),
        ),
        migrations.AlterField(
            model_name='apiimages',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=api.models.get_image_filename, verbose_name='Image'),
        ),
    ]
