# Generated by Django 3.1.5 on 2021-02-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210211_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='tracklet',
            field=models.FileField(default='<django.db.models.fields.files.FileField>_tracklet.txt', null=True, upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='vehicle',
            field=models.FileField(default='<django.db.models.fields.files.FileField>_vehicle.txt', null=True, upload_to='text/'),
        ),
    ]
