# Generated by Django 3.1.3 on 2021-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210212_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='original_video',
            field=models.FileField(default='', upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='tracklet',
            field=models.FileField(default='_tracklet.txt', null=True, upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='api',
            name='vehicle',
            field=models.FileField(default='_vehicle.txt', null=True, upload_to='text/'),
        ),
    ]
