# Generated by Django 3.1.3 on 2021-02-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210215_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='count',
        ),
        migrations.RemoveField(
            model_name='api',
            name='tracklet',
        ),
        migrations.RemoveField(
            model_name='api',
            name='upload_at',
        ),
        migrations.RemoveField(
            model_name='api',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='api',
            name='video_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='original_video',
            field=models.FileField(blank=True, default=None, upload_to='video/'),
        ),
    ]
