# Generated by Django 3.1.3 on 2021-02-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210216_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='tracklet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='video_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ApiTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.api')),
            ],
        ),
    ]
