# Generated by Django 3.1.3 on 2021-02-16 06:15

import api.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210216_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('begin_frame', models.IntegerField()),
                ('exit_frame', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('car_type', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=api.models.get_image_filename, verbose_name='Image')),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.car')),
            ],
        ),
        migrations.AlterField(
            model_name='api',
            name='original_video',
            field=models.FileField(default=None, upload_to='video/'),
        ),
        migrations.DeleteModel(
            name='ApiImages',
        ),
        migrations.AddField(
            model_name='car',
            name='api',
            field=models.ForeignKey(db_column='api', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.api'),
        ),
    ]
