# Generated by Django 3.1.3 on 2021-02-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210216_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='car_type',
        ),
    ]
