# Generated by Django 3.1.3 on 2021-02-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210216_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarImages',
            new_name='CarImage',
        ),
    ]
