# Generated by Django 3.1.6 on 2021-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_api_num_of_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='labeld_video',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='api',
            name='original_video',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
